language: python
sudo: true

python:
  - 3.6.9

services:
  postgresql
addons:
  postgresql: '9.5'

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv sync -d
  - cp contrib/env-exemple .env

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres

script:
  - pipenv run flake8 .
  - pipenv run pytest
#  - pipenv run pytest --cov=app

#after_success:
#  - pipenv run codecov



